### ISSUE TITLE
Error: Access is denied.

### ISSUE THREAD

**Issue by mkody** [sugrocks/cn-schedule#27]
https://sentry.io/ctoon/cn-schedule/issues/345897355/

```
Error: Access is denied.

  at e.a.methods.getSchedule (static/js/app.60e5ae1ff1c750bc101d.js:1452:10)
  at this (./node_modules/vue/dist/vue.esm.js:179)
  at handlers (static/js/app.60e5ae1ff1c750bc101d.js:1498:4)
  at callHook (./node_modules/vue/dist/vue.esm.js:2665)
  at queue (./node_modules/vue/dist/vue.esm.js:3526)
...
(9 additional frame(s) were not displayed)
```

**Comment by mkody** [comment]
This is on IE only.
The hell is this talking about. Maybe I can do a workaround or something.

**Comment by mkody** [comment]
Alright, this one sucks. It's either a registry key and/or some kind of security usually done in enterprises (was that someone slacking off?).
Anyways like for #28, I'll display a message for IE and maybe try to find a way to disable LocalStorage/settings.

https://stackoverflow.com/questions/13102116/access-denied-for-localstorage-in-ie10
